name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4' # Ruby 3.1 버전 사용

      - name: Install Dependencies
        run: |
          gem update --system 3.3.22
          gem install bundler
          bundle install

      # Jekyll 사이트 빌드 및 배포
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          jekyll_src: './'